ROW_CORPUS_NAME = "sample_corpus.tsv"
CLEANED_CORPUS_LIST = "cleaned_corpus_list_50"
CLEANED_CORPUS_TABLE = "cleaned_corpus_table_50"
CLEANED_CORPUS_DICTIONARY = "cleaned_corpus_dictionary_50"
CLEANED_CORPUS_TFIDF = "cleaned_corpus_tfidf_50"
LDA_MODEL = "lda_model"
W2V_MODEL = "w2v_model"